transcription updated

diff --git a/translate b/translate
--- a/translate
+++ b/translate
@@ -49,8 +49,8 @@ declare -r LATIN_LANG=en			#target for all not A-z latin requests			A-z latin al
 declare -r flogin=121212 			#forvo.com login and pass REQUIRED!
 declare -r fpass=121212
 TERMINAL_C="WOB"				#Your terminal - white on black:WOB, black on white:BOW, anything other:O
-#httpproxy="127.0.0.1:4444"		#proxy for long strings
-#httpsproxy="--socks5 127.0.0.1:9050"	#socks5
+httpproxy="127.0.0.1:4444"		#proxy for long strings
+httpsproxy="--socks5 127.0.0.1:9050"	#socks5
 #
 declare -r words_buffer=4000		#4000 files max. there is removeing all files older than 20 days.
 declare -r timeout=6
@@ -271,7 +271,7 @@ eng_sound_download(){ 			# $cachefile,
 			return
 		fi
 	fi
-	echo fail to get sound from forvo.com
+	[ $sound -eq 1 ] && echo fail to get sound from forvo.com
 }
 
 
@@ -414,8 +414,8 @@ else
 			fi
 
 			#transcription
-			trans=$(curl -s --user-agent "$useragent" $httpsproxy -x "$httpproxy" http://lingvopro.abbyyonline.com/en/Translate/en-"$target"/"$request" | grep -o '"[^"]*Handlers/TranscriptionHandler\.ashx[^"]*"' | sed 's/.*=\(.*\)"/\1/'| echo -n -e $(sed 's/+/ /g; s/%/\\x/g')) #getting transcription
-			[[ $? != 0 ]] &&  { echo cant get transcription; bashtrap; }
+			trans=$(curl -s --user-agent "$useragent" $httpsproxy -x "$httpproxy" http://lingvo-online.ru/en/Translate/en-"$target"/"$request" | grep -o '"[^"]*/transcription\.gif.Text=[^"]*"' | sed 's/.*=\(.*\)"/\1/'| echo -n -e $(sed 's/+/ /g; s/%/\\x/g')) #getting transcription
+			[[ $? != 0 ]] &&  { echo "can't get transcription"; bashtrap; }
 			[[ $trans ]] && echo "[$trans]" >> "$cachefile"
 
 			cat "$cachefile" 2>/dev/null #output
