proxy, useragent, volume, comments

diff --git a/translate b/translate
--- a/translate
+++ b/translate
@@ -7,14 +7,6 @@
 # + cache for all words
 # + saving words to file for learning
 
-trap bashtrap INT
-bashtrap()
-{
-	echo "CTRL+C Detected"
-	rm "$cachefile" 2> /dev/null
-	exit
-}
-
 help='translate [-s] <text>
 if text is english, target language is ENGLISH_TARGET_LANG
 otherwise, "target" language is english
@@ -26,8 +18,18 @@ target=en 			#target for all languages except english
 flogin=121212 			#forvo.com login and pass REQUIRED!
 fpass=121212
 words_buffer=3000
-PR_DIR="/home/$USER/.translate"
+httpproxy=""			#proxy
 timeout=5
+PR_DIR="/home/$USER/.translate"
+useragent="Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.34 (KHTML, like Gecko) QupZilla/1.3.1 Safari/534.34"
+#
+trap bashtrap INT
+bashtrap()
+{
+	echo "CTRL+C Detected"
+	rm "$cachefile" 2> /dev/null
+	exit
+}
 
 jsout_dictionary="var googlearr = eval(JSON.stringify(myJSONObject));
 var rsum=\"\"; //translated text
@@ -64,41 +66,44 @@ function dictionary(arr){ //dictionary output
 	}
 }"
 
-request=($*)
+request=($*) #get array
 sound=0
-if [[ $1 = -h || $1 = --help ]]; then
+if [[ $1 = -h || $1 = --help ]]; then #help
 	echo "$help"
 	exit
 fi
-if [[ $1 == -s || $1 == --sound ]];then
+if [[ $1 == -s || $1 == -s2 || $1 == -s3 || $1 == --sound ]];then #sound varibles
 	sound=1
-	request[0]=""
+	[[ $1 == -s2 ]] && volume=2
+	[[ $1 == -s3 ]] && volume=4
+	request[0]="" #remove first parameter
 fi
-request=${request[*]}
+request=${request[*]} #to string
+[[ ${#request} -eq 0 ]] && exit
 
 source=auto
-tchar=${request:0:1}
+tchar=${request:0:1} #language detection by first character
 tcharnum=$(printf "%d" "'${tchar}")
-if [[ $tcharnum -ge 65 && $tcharnum -le 122 ]]; then #if request is english
-	source=en
-	target="$ENGLISH_TARGET_LANG" #if text is english, "target" language is russian
+if [[ $tcharnum -ge 65 && $tcharnum -le 122 ]]; then #if request is A-Za-z then it is english...
+	source=en #english
+	target="$ENGLISH_TARGET_LANG" #if text is english, target language is ENGLISH_TARGET_LANG
 fi
 
 [ ! -d "$PR_DIR" ] && mkdir "$PR_DIR"
 [ ! -d "$PR_DIR"/cache ] && mkdir "$PR_DIR"/cache
 
-r_words_count=$(echo "$request"  |wc -w)
-
 if [[ ${#request} -gt 300 ]]; then
-	result=$(curl -s -i --user-agent "" -d "sl=$source" -d "tl=$target" --data-urlencode "text=$request" http://translate.google.com)
+	result=$(curl -s -i --user-agent "$useragent" -x "$httpproxy" -d "sl=$source" -d "tl=$target" --data-urlencode "text=$request" http://translate.google.com)
 	encoding=$(awk '/Content-Type: .* charset=/ {sub(/^.*charset=["'\'']?/,""); sub(/[ "'\''].*$/,""); print}' <<<"$result")
 	#iconv -f $encoding <<<"$result" | awk 'BEGIN {RS="<div"};/<span[^>]* id=["'\'']?result_box["'\'']?/ {sub(/^.*id=["'\'']?result_box["'\'']?(>| [^>]*>)([ \n\t]*<[^>]*>)*/,"");sub(/<.*$/,"");print}' | html2text -utf8
 	echo -e "\033[32;1m"$(iconv -f $encoding <<<"$result" |  awk 'BEGIN {RS="</div>"};/<span[^>]* id=["'\'']?result_box["'\'']?/' | html2text -utf8)"\033[0m"
 
 else
 	cachefile="$PR_DIR/cache/$request"
+	r_words_count=$(echo "$request"  |wc -w)
 	if [[ ! -e "$cachefile" || (( $sound == 1 && ! -e "$cachefile".mp3 )) ]]; then
-		grespond=$(curl -s -i --user-agent "" --data-urlencode "text=$request" "http://translate.google.com/translate_a/t?client=t&hl=$target&sl=$source&tl=$target&ie=UTF-8&oe=UTF-8&multires=1&ssel=0&tsel=0&sc=1") #getting google respond for short sentence
+		grespond=$(curl -s -i --user-agent "$useragent" -x "$httpproxy" --connect-timeout $timeout -m $timeout --data-urlencode "text=$request" "http://translate.google.com/translate_a/t?client=t&hl=$target&sl=$source&tl=$target&ie=UTF-8&oe=UTF-8&multires=1&ssel=0&tsel=0&sc=1") #getting google respond for short sentence
+		[[ ! $(echo $grespond | grep -o '\[.*\]') ]] && { echo "can't connect" ; exit; } #little connection check
 
 		#echo -n "var myJSONObject = " > "$PR_DIR"/tmpjsobj2
 		#echo [$(echo "$grespond" | grep -o '"[^"]*/i[^"]*"')"];" >> "$PR_DIR"/tmpjsobj2
@@ -126,7 +131,7 @@ else
 
 			js "$PR_DIR"/tmpjsobj > "$cachefile" #google translated text and dictionary to cache
 
-			raw_phras=$(curl -s --user-agent "" http://www.macmillandictionary.com/dictionary/american/"$(echo $request | tr ' ' - )" | grep -o '<li ID.*End of DIV SENSE--></li>' | sed 's/<.\?span[^>]*>//g' )
+			raw_phras=$(curl -s --user-agent "$useragent" -x "$httpproxy" http://www.macmillandictionary.com/dictionary/american/"$(echo $request | tr ' ' - )" | grep -o '<li ID.*End of DIV SENSE--></li>' | sed 's/<.\?span[^>]*>//g' )
 			phras=$(echo $raw_phras |  sed 's/End of DIV SENSE--><\/li>/End of DIV SENSE--><\/li>\n/g' | grep -n -o '"h2">[^>]*<' | sed 's/^\([^:]*\):.*>\([^<]*\).*/\1 \2\./') #getting phrases
 			phras2=$(echo $raw_phras |  sed 's/End of DIV SENSE--><\/li>/End of DIV SENSE--><\/li>\n/g' | grep -n -o '"EXAMPLE">[^>]*<' | sed 's/^\([^:]*\):.*>\([^<]*\).*/\1 \2/') #getting examples
 			if [[ $phras ]]; then
@@ -137,7 +142,7 @@ else
 #				echo -e "\033[34m"http://www.macmillandictionary.com/dictionary/american/"$request"$(tput sgr0) >> "$cachefile"
 			fi
 
-			trans=$(curl -s --user-agent "" http://lingvopro.abbyyonline.com/en/Translate/en-ru/"$request" | grep -o '"[^"]*Handlers/TranscriptionHandler\.ashx[^"]*"' | sed 's/.*=\(.*\)"/\1/'| echo -n -e $(sed 's/+/ /g; s/%/\\x/g')) #getting transcription
+			trans=$(curl -s --user-agent "$useragent" -x "$httpproxy" http://lingvopro.abbyyonline.com/en/Translate/en-ru/"$request" | grep -o '"[^"]*Handlers/TranscriptionHandler\.ashx[^"]*"' | sed 's/.*=\(.*\)"/\1/'| echo -n -e $(sed 's/+/ /g; s/%/\\x/g')) #getting transcription
 			[[ $trans ]] && echo "[$trans]" >> "$cachefile"
 
 			cat "$cachefile" 2>/dev/null #output
@@ -153,10 +158,10 @@ else
 
 				#getting sound (always) from forvo.com
 				if [[ ! -e "$cachefile".mp3 ]]; then
-					curl -s -c "$PR_DIR"/tmpcookie --connect-timeout $timeout -m $timeout --user-agent "" -d "login=$flogin&password=$fpass" http://ru.forvo.com/login/ -o/dev/null
+					curl -s -c "$PR_DIR"/tmpcookie --connect-timeout $timeout -m $timeout --user-agent "$useragent" -x "$httpproxy" -d "login=$flogin&password=$fpass" http://ru.forvo.com/login/ -o/dev/null
 					if [[ -e "$PR_DIR"/tmpcookie ]]; then
-						slink=$(curl -s -b $PR_DIR/tmpcookie --connect-timeout $timeout -m $timeout http://ru.forvo.com/word/"$request"/ | grep -o '[^"]*/download/mp3/'"$request"'/en/[^"]*' |head -n 1 )
-						[[ $slink ]] && curl -s -b "$PR_DIR"/tmpcookie --connect-timeout $timeout -m $timeout --user-agent "" -o "$cachefile".mp3 http://ru.forvo.com"$slink"
+						slink=$(curl -s -b $PR_DIR/tmpcookie --connect-timeout $timeout -m $timeout --user-agent "$useragent" -x "$httpproxy" http://ru.forvo.com/word/"$request"/ | grep -o '[^"]*/download/mp3/'"$request"'/en/[^"]*' |head -n 1 )
+						[[ $slink ]] && curl -s -b "$PR_DIR"/tmpcookie --connect-timeout $timeout -m $timeout --user-agent "$useragent" -x "$httpproxy" -o "$cachefile".mp3 http://ru.forvo.com"$slink"
 						rm "$PR_DIR"/tmpcookie 2>/dev/null
 					else
 						echo fail to get sound from forvo.com
@@ -169,7 +174,7 @@ else
 			[[ $fl ]] && echo $fl #google fixed text output
 
 			if [[ $r_words_count -gt 1 && $r_words_count -le 3 && $source == en && ! $fl && $(echo "$request" | tr '[:upper:]' '[:lower:]') !=  $(echo "$res" | tr '[:upper:]' '[:lower:]') ]]; then #phrases for 2 3 words of phrasal verbs
-				raw_phras=$(curl -s --user-agent "" http://www.macmillandictionary.com/dictionary/american/"$(echo $request | tr ' ' - )" | grep -o '<li.*End of DIV SENSE--></li>' | sed 's/<.\?span[^>]*>//g' )
+				raw_phras=$(curl -s --user-agent "$useragent" -x "$httpproxy" http://www.macmillandictionary.com/dictionary/american/"$(echo $request | tr ' ' - )" | grep -o '<li.*End of DIV SENSE--></li>' | sed 's/<.\?span[^>]*>//g' )
 				phras=$(echo $raw_phras |  sed 's/End of DIV SENSE--><\/li>/End of DIV SENSE--><\/li>\n/g' | grep -n -o '"h2">[^>]*<' | sed 's/^\([^:]*\):.*>\([^<]*\).*/\1 \2\./') #getting phrases
 				phras2=$(echo $raw_phras |  sed 's/End of DIV SENSE--><\/li>/End of DIV SENSE--><\/li>\n/g' | grep -n -o '"EXAMPLE">[^>]*<' | sed 's/^\([^:]*\):.*>\([^<]*\).*/\1 \2/') #getting examples
 				if [[ $phras2 ]]; then
@@ -184,7 +189,7 @@ else
 	fi
 	#sound output
 	if [[ $sound == 1 && -e "$cachefile".mp3 ]]; then 
-		stat=$(playsound --loop 0 "$cachefile".mp3 2>&1 | grep -o 'Couldn')
+		stat=$(playsound --loop 0 --volume "$volume" "$cachefile".mp3 2>&1 | grep -o 'Couldn')
 		[[ $stat ]] && rm "$cachefile".mp3
 	fi
 fi
