english transcription fix

diff --git a/translate b/translate
--- a/translate
+++ b/translate
@@ -578,8 +578,11 @@ main_func(){
 			declare trans
 			if [[ $r_words_count -le 2 && ${#request} -gt 1 && ! $(echo "$difftest" | wc -l) -gt 1 ]];then #special check( expample: advise advice)
 			    if [[ $source == "en" ]];then
-				trans=$(curl -s -m 6 --user-agent "$useragent" $httpsproxy -x "$httpproxy" https://www.collinsdictionary.com/dictionary/english/"$request" | sed -n '0,/.*pron.type/  s/.*pron.type-\">\([^<]*\).*/\1/p') #getting transcription
-			       [[ $? != 0 || $trans == ""  ]] &&  { echo "can't get transcription"; error=1; } #bashtrap;
+				trans=$(curl -s -m 6 --user-agent "$useragent" $httpsproxy -x "$httpproxy" https://www.collinsdictionary.com/dictionary/english/"$request" | grep "pron type-\"" | sed 's/.*pron type-">\([^<]*\)<.*/\1/' ) #getting transcription
+				[[ $? != 0 || $trans == ""  ]] &&  { echo "can't get transcription"; error=1; } #bashtrap;
+				trans1=$(echo "$trans" | head -n 1); #first transcription may be separated to parts
+				trans2=$(echo "$trans" | sed -n 2p);
+				if [ "$trans2" > "$trans1" ] ; then trans=$trans2; else trans=$trans1; fi; #string lenght comparision
 			    elif [[ $source == "de" ]];then
 				reg_for_tr=$(echo $request | sed -e 's/ö/o/g' -e 's/ä/a/g' -e 's/ü/u/g' -e 's/ß/ss/g') #curl UTF-8 combining characters problem
 				#echo $reg_for_tr    #MUST EXIST EVEN IN COMMENT. STRANGE BASH BUG
